export const COLOR_OPTIONS = [
  { value: "#008000", label: "Green" },
  { value: "#3030ff", label: "Blue" },
  { value: "#FF0000", label: "Red" },
  { value: "#FFA500", label: "Orange" },
  { value: "#FFFF00", label: "Yellow" },
  { value: "#00FF00", label: "Lime" },
  { value: "#00FFFF", label: "Cyan" },
  { value: "#800080", label: "Purple" },
  { value: "#FF00FF", label: "Magenta" },
  { value: "#FFC0CB", label: "Pink" },
  { value: "#8B4513", label: "SaddleBrown" },
  { value: "#A52A2A", label: "Brown" },
  { value: "#808080", label: "Gray" },
  { value: "#000000", label: "Black" },
  { value: "#FFFFFF", label: "White" },
];
